baseURL = 'https://commune.ink/'
languageCode = 'en-us'
title = 'Commune'
theme = 'maddybook'

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = 2021
    customCSS = ['commune.css']

[markup.goldmark.renderer]
    unsafe = true
